### ISSUE TITLE
读文献遇到了一些困难 求解答

### ISSUE THREAD

**Issue by oahnah** [DataXujing/YOLOv9#2]
为什么叫做可编程 还有辅助可逆分支是在代码中怎么体现可逆的？

**Comment by DataXujing** [comment]
+ 我认为的PGI paper作者指的是一个全新的模型架构：参考![Figure 3](https://github.com/DataXujing/YOLOv9/blob/main/docs/PGI.png) 
![image](https://github.com/DataXujing/YOLOv9/assets/24708267/19396d86-fdc0-4230-98de-1daf794e7e32)



上图中的(d)即为PGI的模型架构,具体的block是由GELAN堆叠得到的。

+ 所谓的`可逆`是在卷积提取过程中随着层数的增加特征图和梯度丢失了原图像的太多信息，`可逆`是保证信息丢失尽可能最小

+ 作者给的解决办法就是PGI + GELAN, 通过类似于Co-DETR的辅助分支和多级辅助信息，达到`可逆`的目的，其效果如下：
![image](https://github.com/DataXujing/YOLOv9/assets/24708267/e438bc03-5e90-4b54-8907-0f0c671f5875)

比ResNet还要好！

> 注意一点的是：辅助分支只在训练过程中作为监督学习来学习更新模型参数，我们在推断过程中是把辅助分支扔掉了，只用了主分支（TensorRT和NCNN转模型前对onnx模型编辑的时候去掉了辅助分支）！
