### ISSUE TITLE
onnx导出问题

### ISSUE THREAD

**Issue by stackByStack** [DataXujing/YOLOv9#3]
建议将
`python export.py --data=./data/xray.yaml --weights=./runs/train/exp/weights/last.pt --opset=13 --include=onnx --simplify`
替换为`python export.py --data=./data/xray.yaml --weights=./runs/train/exp/weights/last.pt --include=onnx --simplify`
默认opset为12
经过多次测试，使用前者导出的模型无法使用，效果很差.

**Comment by DataXujing** [comment]
我暂时没有复现出你说的问题，如果使用NCNN部署，建议使用PNNX.

**Comment by stackByStack** [comment]
好的，我再试试

**Comment by aaafdsf** [comment]
> 好的，我再尝尝

方便加个QQ交流不 QQ275173418
